// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type GetBalanceByCoinReq struct {
	ChainName string `json:"chainName" `
}

type GetBalanceByCoinResp struct {
	CoinType        string                 `json:"coinType"`
	CoinObjectCount int                    `json:"coinObjectCount"`
	TotalBalance    string                 `json:"totalBalance"`
	LockedBalance   map[string]interface{} `json:"lockedBalance"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type MgoTransaction struct {
	ID          int64  `json:"id"`
	Digest      string `json:"digest"`
	From        string `json:"from"`
	To          string `json:"to"`
	Amount      string `json:"amount,omitempty"`
	FromAmount  string `json:"from_amount,omitempty"`
	Checkpoint  string `json:"checkpoint,omitempty"`
	CoinType    string `json:"coin_type,omitempty"`
	GasOwner    string `json:"gas_owner,omitempty"`
	GasPrice    string `json:"gas_price,omitempty"`
	GasBudget   string `json:"gas_budget,omitempty"`
	TimestampMs string `json:"timestamp_ms,omitempty"`
}

type RegisterRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type TransactionListReq struct {
	Page      int    `json:"page"`
	PageSize  int    `json:"pageSize"`
	ChainName string `json:"chainName"`
	Type      int    `json:"type"`
}

type TransactionListResp struct {
	Page     int              `json:"page"`
	PageSize int              `json:"pageSize"`
	Total    int64            `json:"total"`
	List     []MgoTransaction `json:"list"`
}

type UserResponse struct {
	Id            int64  `json:"id"`
	Username      string `json:"username"`
	MgoAddress    string `json:"mgo_address"`
	SolanaAddress string `json:"solana_address"`
	Token         string `json:"token,omitempty"`
}

type WithdrawalReq struct {
	ToAddress string  `json:"toAddress"`
	ChainName string  `json:"chainName"`
	Amount    float64 `json:"amount"`
}

type WithdrawalResp struct {
	Hash string `json:"hash"`
}
