// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	common "user/internal/handler/common"
	"user/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/balance",
				Handler: serverCtx.AuthMiddleware(common.BalanceHandler(serverCtx)),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: common.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: common.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/transaction",
				Handler: serverCtx.AuthMiddleware(common.TransactionHandler(serverCtx)),
			},
			{
				Method:  http.MethodPost,
				Path:    "/withdrawal",
				Handler: serverCtx.AuthMiddleware(common.WithdrawalHandler(serverCtx)),
			},
		},
		rest.WithPrefix("/v1"),
	)
}
